### ISSUE TITLE
Alternative to broadcasting

### ISSUE THREAD

**Issue by michael-the1** [michael-the1/tsukiji#1]
Currently uses broadcasting.

Consider using subset view, nearest neighbour.

**Comment by Yuugoh** [comment]
So the issue that arises with using broadcasting is scaling. The problem that comes with using a protocol where one peer hears information about other peers from a single or a subset of peers is competition. 

When Alice is telling Bob of what offers currently exist on the market, it is highly profitable for Alice to lie about any other offer that is more attractive than her own. There are several possible approaches to attempt to solve this issue.
-Make it impossible to lie about recieved information.
-Make it unprofitable to lie about recieved information.
-Punish liars when they are discovered.
-Recieve information from multiple peers that should be the same, and deem any peers that don't have the same information as the majority a liar.

These approaches offer options to solve the issue. Now we need to design implementations of these solutions that are practical in a decentralised system.

**Comment by Yuugoh** [comment]
The chosen solution to the issue is the gossip protocol. Peers now only tell their message to a subgroup of other peers, rather than every peer. Whenever a message is received, they relay the message to every peer they know, not every peer existing in the network.

We have chosen to not address the issue of liars in the network yet, this may or may not be solved later in development.
